---
- name: Voeg A-record toe aan Cloudflare voor AWX-instanties
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    cloudflare_api_token: "T463_cr0jNMDrUuV3ndODCyxGPASgcrr1bBQX6mG"
    cloudflare_zone_id: "cafd6808498a39b169edf97536f2cbdf"
    domain: "rafikiserver.nl"
    awx_api_token: "MoWalW6XysmG6hWmVB1tWHM3HhWhkW"
    inventory_id: 2  # AWX inventory ID

  tasks:
    - name: Verkrijg AWX hosts en IP's
      uri:
        url: "http://185.107.90.120:31151/api/v2/inventories/{{ inventory_id }}/hosts/"
        headers:
          Authorization: "Bearer {{ awx_api_token }}"
        return_content: yes
      register: awx_host_data

    - name: Verkrijg bestaande DNS-records van Cloudflare
      uri:
        url: "https://api.cloudflare.com/client/v4/zones/{{ cloudflare_zone_id }}/dns_records"
        method: GET
        headers:
          Authorization: "Bearer {{ cloudflare_api_token }}"
        return_content: yes
      register: cloudflare_records

    - name: Controleer of het A-record al bestaat
      set_fact:
        record_exists: "{{ cloudflare_records.json.result | selectattr('name', 'equalto', item.description) | selectattr('content', 'equalto', item.name) | list | length > 0 }}"
      loop: "{{ awx_host_data.json.results }}"
      when: cloudflare_records.json.result is defined

    - name: Voeg A-record toe aan Cloudflare als het nog niet bestaat
      uri:
        url: "https://api.cloudflare.com/client/v4/zones/{{ cloudflare_zone_id }}/dns_records"
        method: POST
        headers:
          Authorization: "Bearer {{ cloudflare_api_token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          type: A
          name: "{{ item.description }}"
          content: "{{ item.name }}"
          ttl: 1  # automatisch
          proxied: true  # Oranje wolk aan
        status_code: 200
      when: not record_exists
      loop: "{{ awx_host_data.json.results }}"

    - name: Toon de resultaten van Cloudflare updates
      debug:
        var: result.json
