---
- name: Voeg A-record toe aan Cloudflare voor AWX-instanties
  hosts: localhost
  gather_facts: no
  vars:
    cloudflare_api_token: "T463_cr0jNMDrUuV3ndODCyxGPASgcrr1bBQX6mG"
    cloudflare_zone_id: "cafd6808498a39b169edf97536f2cbdf"
    domain: "rafikiserver.nl"
    awx_api_token: "MoWalW6XysmG6hWmVB1tWHM3HhWhkW"
    inventory_id: 2  # AWX inventory ID

  tasks:
    - name: Verkrijg AWX hosts en IP's
      uri:
        url: "http://185.107.90.120:31151/api/v2/inventories/{{ inventory_id }}/hosts/"
        headers:
          Authorization: "Bearer {{ awx_api_token }}"
        return_content: yes
      register: awx_host_data

    - name: Voeg A-record toe aan Cloudflare
      uri:
        url: "https://api.cloudflare.com/client/v4/zones/{{ cloudflare_zone_id }}/dns_records"
        method: POST
        headers:
          Authorization: "Bearer {{ cloudflare_api_token }}"
          Content-Type: "application/json"
        body_format: json
        body:
          type: A
          name: "{{ item.name }}"
          content: "{{ item.ipv4 }}"
          ttl: 1  # automatisch
          proxied: true  # Oranje wolk aan
        status_code: 200
      with_items: "{{ awx_host_data.json.results }}"
      when: item.ipv4 is defined

    - name: Toon de resultaten van Cloudflare updates
      debug:
        var: result.json
