---
- name: Automate Plesk reseller account creation and send email
  hosts: 37.128.150.202
  gather_facts: no
  vars:
    client_email: "sefu@live.nl"
    client_username: "sefu@live.nl"
    client_password: "reseller_password"
    client_domain_limit: 4
    client_email_limit: 50
    smtp_host: "mail.rafikihosting.nl"
    smtp_port: 465
    smtp_username: "sales@rafikihosting.nl"
    smtp_password: "Welkom123!?"
    server_ip: "vps689.rafikiserver.nl"
    server_hostname: "vps689.rafikiserver.nl"
    from_email: "sales@rafikihosting.nl"
    subject_line: "Oplevering van jouw Managed VPS ({{ server_hostname }})"

  tasks:
    - name: Check if reseller already exists
      ansible.builtin.shell: |
        plesk bin reseller --info {{ client_username }}
      register: reseller_check
      ignore_errors: yes

    - name: Create reseller account via Plesk shell command
      ansible.builtin.shell: |
        plesk bin reseller --create {{ client_username }} -passwd {{ client_password }} -email {{ client_email }} -role reseller -domains {{ client_domain_limit }} -mail {{ client_email_limit }}
      when: reseller_check.rc != 0
      become: yes
      become_method: sudo

    - name: Send email to client
      mail:
        host: "{{ smtp_host }}"
        port: "{{ smtp_port }}"
        username: "{{ smtp_username }}"
        password: "{{ smtp_password }}"
        to: "{{ client_email }}"
        from: "{{ from_email }}"
        subject: "{{ subject_line }}"
        body: |
          Geachte klant,

          We zijn verheugd je te kunnen informeren dat je Managed VPS succesvol is opgezet en klaar voor gebruik. Hieronder vind je de toegangsinformatie:

          Plesk Paneel: https://{{ server_hostname }}:8443
          Gebruikersnaam: {{ client_username }}
          Wachtwoord: {{ client_password }}

          Je hebt de volgende resources toegewezen gekregen:
          - RAM: 4GB
          - CPU: 4 Cores
          - Domeinen: {{ client_domain_limit }}
          - E-mailaccounts: {{ client_email_limit }}
          - Updates/Onderhoud 
          - Monitoring
          - Beveiliging
          - WP-Rocket
          - Managed Back-ups:
          
        

          Als je vragen hebt of hulp nodig hebt, aarzel dan niet om contact op te nemen met onze klantenservice.

          Bedankt voor het kiezen van Rafiki Hosting!

          Met vriendelijke groet,
          
          Het Rafiki Hosting Team
