---
- name: VPS aanmaken via Contabo API
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Nieuwe VPS aanmaken op Contabo
      uri:
        url: "https://api.contabo.com/v1/instances"
        method: POST
        headers:
          Authorization: "Bearer T463_cr0jNMDrUuV3ndODCyxGPASgcrr1bBQX6mG"
          Content-Type: "application/json"
        body:
          productId: "V699"  # Specifieke productId, bijv. V96 voor jouw VPS product
          region: "EU"  # Altijd EU
          imageId: "afecbb85-e2fc-46f0-9684-b46b1faf00bb"  # Ubuntu 22.04
          rootPassword: "Bilspleet21?"  # Rootwachtwoord
          period: 1  # Altijd 1 maand
          displayName: "vps{{ ansible_date_time.iso8601_basic }}"  # Naam met datumstempel
          userData: ""  # Optionele Cloud-Init configuratie
        body_format: json
        status_code: 200
      register: vps_creation

    - name: Toon resultaat van VPS aanmaak
      debug:
        msg: "VPS aangemaakt: {{ vps_creation.json }}"
