---
- name: Nieuwe VPS aanmaken op Contabo
  hosts: localhost
  connection: local
  tasks:
    - name: Verkrijg API-token van Contabo
      uri:
        url: "https://auth.contabo.com/auth/realms/contabo/protocol/openid-connect/token"
        method: POST
        headers:
          Content-Type: "application/x-www-form-urlencoded"
        body:
          client_id: "INT-13273960"
          client_secret: "rJMKuzUtEDNqYCr23NY6Qn3mhTZCqrJQ"
          username: "support@rafikihosting.nl"
          password: "Bilspleet21?"
          grant_type: "password"
        return_content: yes
      register: token_response

    - name: Zet het API-token in een variabele
      set_fact:
        access_token: "{{ token_response.json.access_token }}"

    - name: Maak VPS aan op Contabo
      uri:
        url: "https://api.contabo.com/v1/compute/instances"
        method: POST
        headers:
          Authorization: "Bearer {{ access_token }}"
          Content-Type: "application/json"
        body:
          region: "EU"
          productId: "V69"
          imageId: "afecbb85-e2fc-46f0-9684-b46b1faf00bb"
          period: 1
          displayName: "vps408.rafikiserver.nl"
          rootPassword: "Bilspleet21?"
        return_content: yes
      register: vps_creation_response

    - name: Toon VPS creatie resultaat
      debug:
        msg: "{{ vps_creation_response }}"
