---
- name: Nieuwe VPS aanmaken op Contabo
  hosts: localhost
  gather_facts: no
  connection: local
  tasks:
    - name: Genereer een willekeurig getal voor de VPS naam
      set_fact:
        vps_naam: "vps{{ 100 + (lookup('pipe', 'date +%s') | int) % 900 }}.rafikiserver.nl"
    
    - name: Nieuwe VPS aanmaken op Contabo
      uri:
        url: "https://api.contabo.com/v1/compute/instances"
        method: POST
        headers:
          Content-Type: "application/json"
          Authorization: "Bearer T463_cr0jNMDrUuV3ndODCyxGPASgcrr1bBQX6mG"
          x-request-id: "{{ lookup('pipe', 'uuidgen') }}"
          x-trace-id: "123213"
        body:
          imageId: "afecbb85-e2fc-46f0-9684-b46b1faf00bb"
          productId: "V69"
          region: "EU"
          sshKeys: []
          rootPassword: "Bilspleet21?"
          period: 1
          displayName: "{{ vps_naam }}"
        body_format: json
        status_code: 201
      register: vps_response

    - name: Geef de respons van de VPS aanmaak weer
      debug:
        var: vps_response
