---
- name: Nieuwe VPS aanmaken op Contabo
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Set datum en tijd voor de VPS naam
      set_fact:
        current_date: "{{ ansible_date_time.iso8601 }}"

    - name: Nieuwe VPS aanmaken op Contabo
      uri:
        url: "https://api.contabo.com/v1/instances"
        method: POST
        headers:
          Authorization: "Bearer {{ contabo_api_token }}"
          Content-Type: "application/json"
        body:
          imageId: "afecbb85-e2fc-46f0-9684-b46b1faf00bb"
          productId: "V69"
          region: "EU"
          sshKeys: []
          rootPassword: "Bilspleet21?"
          period: 1
          displayName: "vps_{{ current_date }}"
          userData: "#cloud-config\nhostname: vps_{{ current_date }}"
        body_format: json
        status_code: 201
      register: create_vps_response

    - name: Toon het antwoord van Contabo
      debug:
        var: create_vps_response
