---
- name: Voeg AWX-host IP's toe aan Prometheus-configuratie
  hosts: localhost
  gather_facts: no
  connection: local
  vars:
    awx_api_token: "MoWalW6XysmG6hWmVB1tWHM3HhWhkW"
    inventory_id: 2  # AWX inventory ID
    prometheus_config_path: "/etc/prometheus/prometheus.yml"
    prometheus_server_ip: "185.95.13.41"
    ansible_ssh_user: "root"  # SSH-gebruiker
    ansible_ssh_pass: "sefuisbaas.nl"  # SSH-wachtwoord
  tasks:
    - name: Verkrijg AWX hosts en IP's
      uri:
        url: "http://185.107.90.120:31151/api/v2/inventories/{{ inventory_id }}/hosts/"
        headers:
          Authorization: "Bearer {{ awx_api_token }}"
        return_content: yes
      register: awx_host_data

    - name: Verzamel de IP's van de hosts
      set_fact:
        ip_addresses: "{{ awx_host_data.json.results | selectattr('name', 'defined') | map(attribute='name') | list }}"

    - name: Update Prometheus-configuratie met nieuwe IP's
      ansible.builtin.lineinfile:
        path: "{{ prometheus_config_path }}"
        regexp: '^scrape_configs:'
        line: |
          scrape_configs:
            - job_name: 'node_exporter'
              static_configs:
                {% for ip in ip_addresses %}
                - targets: ['{{ ip }}:9100']   # {{ ip }}
                {% endfor %}
      delegate_to: "{{ prometheus_server_ip }}"
      become: yes
      become_user: root

    - name: Herstart Prometheus service
      ansible.builtin.systemd:
        name: prometheus
        state: restarted
      delegate_to: "{{ prometheus_server_ip }}"
      become: yes
      become_user: root
