---
- name: Update Prometheus configuration with new IPs from AWX
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    awx_api_token: "MoWalW6XysmG6hWmVB1tWHM3HhWhkW"
    inventory_id: 2  # AWX inventory ID
    prometheus_server_ip: "185.95.13.41"
    prometheus_config_path: "/etc/prometheus/prometheus.yml"

  tasks:
    - name: Verkrijg AWX hosts en IP's
      uri:
        url: "http://185.107.90.120:31151/api/v2/inventories/{{ inventory_id }}/hosts/"
        headers:
          Authorization: "Bearer {{ awx_api_token }}"
        return_content: yes
      register: awx_host_data

    - name: Verzamel de IP's van de hosts
      set_fact:
        new_ips: "{{ awx_host_data.json.results | selectattr('name', 'defined') | map(attribute='name') | list }}"

    - name: Verbind via SSH naar de Prometheus server en pas configuratie aan
      ansible.builtin.ssh:
        host: "{{ prometheus_server_ip }}"
        user: root
        password: "sefuisbaas.nl"
        command: |
          # Controleer en werk Prometheus config bij met de nieuwe IP's
          echo "scrape_configs:" > {{ prometheus_config_path }}
          echo "  - job_name: 'node_exporter'" >> {{ prometheus_config_path }}
          echo "    static_configs:" >> {{ prometheus_config_path }}
          {% for ip in new_ips %}
          echo "      - targets: ['{{ ip }}:9100']" >> {{ prometheus_config_path }}
          {% endfor %}
          echo "      # Voeg meer configuraties toe indien nodig" >> {{ prometheus_config_path }}

    - name: Herstart Prometheus service
      ansible.builtin.systemd:
        name: prometheus
        state: restarted
