---
- name: Configure firewall with basic rules
  hosts: plesk_servers
  become: yes
  tasks:
    - name: Install UFW if not present
      apt:
        name: ufw
        state: present
    - name: Enable UFW
      ufw:
        state: enabled
    - name: Allow essential ports
      ufw:
        rule: allow
        name: "{{ item }}"
      loop:
        - '22'
        - '80'
        - '443'
    - name: Enable UFW default rules
      ufw:
        default: allow
        direction: incoming
      loop:
        - 'allow'
        - 'deny'
