---
- name: Install Prometheus monitoring tools
  hosts: all
  become: yes
  tasks:

    # Install Prometheus and node_exporter dependencies
    - name: Install required dependencies for Prometheus
      apt:
        name:
          - software-properties-common
          - apt-transport-https
          - ca-certificates
        state: present
      when: ansible_os_family == "Debian"

    # Install Prometheus
    - name: Install Prometheus
      apt:
        name: prometheus
        state: present

    # Install node_exporter for Prometheus monitoring
    - name: Install node_exporter
      apt:
        name: prometheus-node-exporter
        state: present

    # Enable and start Prometheus service
    - name: Enable and start Prometheus service
      service:
        name: prometheus
        state: started
        enabled: yes

    # Enable and start node_exporter service
    - name: Enable and start node_exporter service
      service:
        name: prometheus-node-exporter
        state: started
        enabled: yes

    # Open Prometheus port 9090 in UFW
    - name: Open Prometheus port 9090 in UFW
      ufw:
        rule: allow
        proto: tcp
        port: 9090

    # Open node_exporter port 9100 in UFW (optional if needed)
    - name: Open node_exporter port 9100 in UFW
      ufw:
        rule: allow
        proto: tcp
        port: 9100

    # Enable UFW to start on boot
    - name: Enable UFW
      ufw:
        state: enabled
        logging: on
