---
- name: Configure Plesk after installation
  hosts: all
  become: yes
  tasks:

    # Set Plesk admin email
    - name: Set Plesk admin email
      command: /usr/local/psa/bin/admin --update -email support@rafikihosting.nl



    # Register Plesk with paid license
    - name: Register Plesk with paid license
      command: /usr/sbin/plesk bin license --install "A00T00-GDEM10-QH3S91-E74V71-M8BN39"

