- name: Installeer en activeer PHP-versies in Plesk (7.4 en hoger)
  hosts: all
  become: yes
  tasks:
    - name: Haal de huidige PHP-handlers op
      command: plesk bin php_handler --list
      register: php_handlers_output
      changed_when: false

    - name: Installeer PHP 7.4 als deze nog niet geïnstalleerd is
      command: plesk installer --install-component php7.4
      when: "'php7.4' not in php_handlers_output.stdout"
      register: php74_installed
      failed_when: php74_installed.rc != 0

    - name: Installeer PHP 8.0 als deze nog niet geïnstalleerd is
      command: plesk installer --install-component php8.0
      when: "'php8.0' not in php_handlers_output.stdout"
      register: php80_installed
      failed_when: php80_installed.rc != 0

    - name: Installeer PHP 8.1 als deze nog niet geïnstalleerd is
      command: plesk installer --install-component php8.1
      when: "'php8.1' not in php_handlers_output.stdout"
      register: php81_installed
      failed_when: php81_installed.rc != 0

    - name: Installeer PHP 8.2 als deze nog niet geïnstalleerd is
      command: plesk installer --install-component php8.2
      when: "'php8.2' not in php_handlers_output.stdout"
      register: php82_installed
      failed_when: php82_installed.rc != 0

    - name: Installeer PHP 8.3 als deze nog niet geïnstalleerd is
      command: plesk installer --install-component php8.3
      when: "'php8.3' not in php_handlers_output.stdout"
      register: php83_installed
      failed_when: php83_installed.rc != 0

    - name: Installeer PHP 8.4 als deze nog niet geïnstalleerd is
      command: plesk installer --install-component php8.4
      when: "'php8.4' not in php_handlers_output.stdout"
      register: php84_installed
      failed_when: php84_installed.rc != 0

    - name: Activeer PHP 7.4 als deze is geïnstalleerd
      command: plesk bin php_handler --enable -id plesk-php7.4
      when: "'plesk-php7.4' in php_handlers_output.stdout"
      failed_when: false

    - name: Activeer PHP 8.0 als deze is geïnstalleerd
      command: plesk bin php_handler --enable -id plesk-php8.0
      when: "'plesk-php8.0' in php_handlers_output.stdout"
      failed_when: false

    - name: Activeer PHP 8.1 als deze is geïnstalleerd
      command: plesk bin php_handler --enable -id plesk-php8.1
      when: "'plesk-php8.1' in php_handlers_output.stdout"
      failed_when: false

    - name: Activeer PHP 8.2 als deze is geïnstalleerd
      command: plesk bin php_handler --enable -id plesk-php8.2
      when: "'plesk-php8.2' in php_handlers_output.stdout"
      failed_when: false

    - name: Activeer PHP 8.3 als deze is geïnstalleerd
      command: plesk bin php_handler --enable -id plesk-php8.3
      when: "'plesk-php8.3' in php_handlers_output.stdout"
      failed_when: false

    - name: Activeer PHP 8.4 als deze is geïnstalleerd
      command: plesk bin php_handler --enable -id plesk-php8.4
      when: "'plesk-php8.4' in php_handlers_output.stdout"
      failed_when: false

  handlers:
    - name: Herstart Plesk
      service:
        name: psa
        state: restarted
