---
- name: Configure Plesk after installation
  hosts: all
  become: yes
  tasks:

    # Set Plesk admin name
    - name: Set Plesk admin name
      command: /usr/local/psa/bin/admin --update admin -fullname "RH Operations"

    # Set Plesk admin email
    - name: Set Plesk admin email
      command: /usr/local/psa/bin/admin --update admin -email "support@rafikihosting.nl"

    # Set Plesk admin password
    - name: Set Plesk admin password
      command: /usr/local/psa/bin/admin --update admin -passwd "Bilspleet21?"

    # Change Plesk language to Dutch (nl)
    - name: Set Plesk language to Dutch
      command: /usr/local/psa/bin/plesk bin config --set lang nl
