- name: Activeer en installeer gewenste PHP-versies in Plesk (7.4 en hoger)
  hosts: all
  become: yes
  tasks:
    - name: Controleer welke PHP-versies al geïnstalleerd zijn
      command: plesk bin php_handler --list
      register: php_handlers_output
      changed_when: false

    - name: Installeer gewenste PHP-versies (7.4, 8.0, 8.1, 8.2, 8.3, 8.4)
      command: plesk installer --install-component php{{ item }}
      with_items:
        - 7.4
        - 8.0
        - 8.1
        - 8.2
        - 8.3
        - 8.4
      when: "'php{{ item }}' not in php_handlers_output.stdout"
      notify:
        - Herstart Plesk

    - name: Activeer de gewenste PHP-versies
      command: plesk bin php_handler --enable -id plesk-php{{ item }}
      with_items:
        - 7.4
        - 8.0
        - 8.1
        - 8.2
        - 8.3
        - 8.4
      when: "'plesk-php{{ item }}' not in php_handlers_output.stdout"

  handlers:
    - name: Herstart Plesk
      service:
        name: psa
        state: restarted
