---
- name: Install monitoring tools (Grafana, Prometheus)
  hosts: all
  become: yes
  tasks:
    
    # Install Grafana and Prometheus dependencies
    - name: Install required dependencies for Grafana and Prometheus
      apt:
        name:
          - software-properties-common
          - apt-transport-https
          - ca-certificates
        state: present
      when: ansible_os_family == "Debian"

    # Add Grafana APT repository and GPG key
    - name: Add Grafana APT repository
      apt_repository:
        repo: "deb https://packages.grafana.com/oss/deb stable main"
        state: present
        filename: "grafana"
        update_cache: yes

    - name: Add Grafana GPG key
      apt_key:
        url: "https://packages.grafana.com/gpg.key"
        state: present

    # Install Grafana
    - name: Install Grafana
      apt:
        name: grafana
        state: present

    # Install Prometheus
    - name: Install Prometheus
      apt:
        name: prometheus
        state: present

    # Install node_exporter for Prometheus monitoring
    - name: Install node_exporter
      apt:
        name: prometheus-node-exporter
        state: present

    # Enable and start Grafana service
    - name: Enable and start Grafana service
      service:
        name: grafana-server
        state: started
        enabled: yes

    # Enable and start Prometheus service
    - name: Enable and start Prometheus service
      service:
        name: prometheus
        state: started
        enabled: yes

    # Enable and start node_exporter service
    - name: Enable and start node_exporter service
      service:
        name: prometheus-node-exporter
        state: started
        enabled: yes

    # Open Grafana and Prometheus ports (3000 and 9090 respectively)
    - name: Open Grafana port 3000 in UFW
      ufw:
        rule: allow
        proto: tcp
        port: 3000

    - name: Open Prometheus port 9090 in UFW
      ufw:
        rule: allow
        proto: tcp
        port: 9090

    # Ensure UFW is enabled after configuring monitoring ports
    - name: Enable UFW
      ufw:
        state: enabled
