---
- name: Activeer meerdere PHP-versies in Plesk
  hosts: all
  become: true
  tasks:
    - name: Haal huidige PHP-handlers op
      shell: plesk bin php_handler --list
      register: php_handlers_output

    - name: Toon actieve/inactieve PHP-handlers
      debug:
        var: php_handlers_output.stdout_lines

    - name: Definieer gewenste PHP-versies
      set_fact:
        php_versions:
          - 8.4
          - 8.3
          - 8.2
          - 8.1
          - 8.0
          - 7.4
          - 7.3
          - 7.2
          - 7.1
          - 7.0

    - name: Activeer PHP-versies als ze zijn geïnstalleerd maar nog niet actief
      shell: |
        handler_id=$(plesk bin php_handler --list | grep "php{{ item }}" | awk '{print $1}')
        if [ -n "$handler_id" ]; then
          plesk bin php_handler --enable -id "$handler_id"
        fi
      loop: "{{ php_versions }}"
      when: >
        php_handlers_output.stdout is search("php" ~ item ~ " ")
        and
        php_handlers_output.stdout is search("php" ~ item ~ " off")
