---
- name: Run Plesk repair tool
  hosts: all
  become: yes
  tasks:
    - name: Run Plesk repair
      command: plesk repair all --restore
      register: repair_status
      failed_when: repair_status.rc != 0

    - name: Show repair status
      debug:
        msg: "{{ repair_status.stdout }}"
