---
- name: Installeer en activeer gewenste PHP-versies in Plesk
  hosts: all
  become: yes

  tasks:
    - name: Installeer PHP-versies via Plesk CLI
      shell: |
        plesk installer add --components php{{ item }}
      loop:
        - 8.4
        - 8.3
        - 8.2
        - 8.1
        - 8.0
        - 7.4
        - 7.3
        - 7.2
        - 7.1
        - 7.0

    - name: Activeer PHP van OS-leverancier in Plesk
      shell: |
        plesk bin php_handler --enable -id "$(plesk bin php_handler --list | grep 'os' | awk '{print $1}')"
