---
- name: Configure Plesk after installation
  hosts: all
  become: yes
  tasks:

    - name: Set Plesk admin password
      command: /usr/local/psa/bin/admin --set-password -passwd 'Bilspleet21?'

    - name: Set Plesk admin name and email
      command: /usr/local/psa/bin/admin -u -email support@rafikihosting.nl -cname "RH Operations"

    - name: Register Plesk with trial license
      command: /usr/local/psa/bin/license --retrieve

    - name: Set Plesk language to Dutch
      command: /usr/local/psa/bin/admin -u -interface_locale nl-NL
