---
- name: Activeer meerdere PHP-versies in Plesk
  hosts: all
  become: yes
  tasks:
    - name: Haal huidige PHP-handlers op
      command: plesk bin php_handler --list
      register: php_handlers_output
      changed_when: false

    - name: Toon actieve/inactieve PHP-handlers
      debug:
        msg: "{{ php_handlers_output.stdout_lines }}"

    - name: Definieer gewenste PHP-versies
      set_fact:
        php_versions:
          - "7.0"
          - "7.1"
          - "7.2"
          - "7.3"
          - "7.4"
          - "8.0"
          - "8.1"
          - "8.2"
          - "8.3"
          - "8.4"

    - name: Activeer PHP-versies die geïnstalleerd zijn maar nog niet actief
      shell: |
        plesk bin php_handler --enable -id "$(plesk bin php_handler --list | grep 'plesk-php{{ item }}' | awk '{print $1}')"
      with_items: "{{ php_versions }}"
      when: "'plesk-php{{ item }}' not in php_handlers_output.stdout"
      register: enable_php_handlers
      ignore_errors: true

    - name: Verifieer of PHP-handlers ingeschakeld zijn
      command: plesk bin php_handler --list
      register: verify_php_handlers
      changed_when: false

    - name: Toon de lijst van ingeschakelde PHP-versies
      debug:
        msg: "{{ verify_php_handlers.stdout_lines }}"
