---
- name: Configure Plesk after installation
  hosts: all
  become: yes
  tasks:

    # Set Plesk admin password
    - name: Set Plesk admin password
      command: /usr/local/psa/bin/admin --set-password -passwd 'Bilspleet21?'

    # Set Plesk admin name and email
    - name: Set Plesk admin name and email
      command: /usr/local/psa/bin/admin --update -name "RH Operations" -email "support@rafikihosting.nl"

    # Register Plesk with trial license
    - name: Register Plesk with trial license
      command: /usr/local/psa/bin/license --retrieve

    # Set Plesk interface language to Dutch
    - name: Set Plesk language to Dutch
      command: /usr/local/psa/bin/admin --update -interface_locale nl-NL
