---
- name: Configure Prometheus to scrape node_exporter
  hosts: prometheus_server
  become: yes
  tasks:
    - name: Update Prometheus configuration file
      lineinfile:
        path: /etc/prometheus/prometheus.yml
        regexp: '^  - targets:'
        line: '  - targets: ["{{ item }}:9100"]'
      with_items:
        - 192.168.1.100
        - 192.168.1.101

    - name: Restart Prometheus service
      systemd:
        name: prometheus
        state: restarted
