---
- name: Voeg hosts toe aan AWX met hostname als naam en beschrijving
  hosts: all
  gather_facts: false
  tasks:
    - name: Haal de lijst van hostnamen op uit bestand
      slurp:
        src: "/var/www/vhosts/rafikihosting.nl/httpdocs/serverlijst.txt"  # Pas dit pad aan indien nodig
      register: file_content

    - name: Zet de inhoud van het bestand om naar tekst
      set_fact:
        hostname_data: "{{ file_content.content | b64decode | split('\n') }}"  # Gebruik split('\n') om de tekst in regels te splitsen

    - name: Parseer de hostnamen
      set_fact:
        hostnames: "{{ hostname_data | map('trim') | selectattr('0', '!=', '') | list }}"  # Filter lege regels

    - name: Haal de bestaande hosts op uit de AWX-inventaris
      uri:
        url: "http://185.107.90.120:31151/api/v2/hosts/"
        method: GET
        headers:
          Authorization: "Bearer MoWalW6XysmG6hWmVB1tWHM3HhWhkW"
        status_code: 200
        return_content: yes
      register: response
      changed_when: false

    - name: Maak lijst van bestaande hostnamen in AWX
      set_fact:
        existing_hosts: "{{ response.json.results | map(attribute='name') | list }}"

    - name: Voeg nieuwe hosts toe aan AWX via de API
      uri:
        url: "http://185.107.90.120:31151/api/v2/hosts/"
        method: POST
        headers:
          Content-Type: "application/json"
          Authorization: "Bearer MoWalW6XysmG6hWmVB1tWHM3HhWhkW"
        body: "{{ {'inventory': 2, 'name': item, 'description': item} | to_json }}"  # Gebruik hostname als naam en beschrijving
        body_format: json
        status_code: 201
      loop: "{{ hostnames }}"
      when: 
        - item not in existing_hosts  # Controleer of de host al voorkomt in de lijst van bestaande hosts

    - name: Output dat de host al bestaat
      debug:
        msg: "Host {{ item }} bestaat al in de inventaris"
      loop: "{{ hostnames }}"
      when: 
        - item in existing_hosts  # Output als de host al bestaat
