---
- name: Voeg hosts toe aan AWX met IP als naam en hostnaam als omschrijving
  hosts: all
  gather_facts: false
  tasks:
    - name: Haal de lijst van hostnamen en IP-adressen op uit bestand
      slurp:
        src: "/var/www/vhosts/rafikihosting.nl/httpdocs/serverlijst.txt"  # Pas dit pad aan indien nodig
      register: file_content

    - name: Zet de inhoud van het bestand om naar tekst
      set_fact:
        ip_data: "{{ file_content.content | b64decode | splitlines() }}"

    - name: Parseer de IP-adressen en hostnamen
      set_fact:
        hosts: "{{ ip_data | map('split', ' ') | map('first') | list }}"
        descriptions: "{{ ip_data | map('split', ' ') | map('last') | list }}"

    - name: Voeg hosts toe aan AWX inventaris
      awx.awx.inventory_host:
        inventory: "Managed Plesk Servers"
        host: "{{ item.0 }}"
        description: "{{ item.1 }}"
        state: present
      loop: "{{ hosts | zip(descriptions) | list }}"
