---
- name: Voeg hosts toe aan AWX met IP als naam en hostnaam als omschrijving
  hosts: all
  gather_facts: false
  tasks:
    - name: Haal de lijst van hostnamen en IP-adressen op uit bestand
      slurp:
        src: "/var/www/vhosts/rafikihosting.nl/httpdocs/serverlijst.txt"  # Pas dit pad aan indien nodig
      register: file_content

    - name: Zet de inhoud van het bestand om naar tekst
      set_fact:
        ip_data: "{{ file_content.content | b64decode | to_nice_yaml | split('\n') }}"  # Gebruik split() na b64decode

    - name: Parseer de IP-adressen en hostnamen
      set_fact:
        hosts: "{{ ip_data | map('split', ' ') | map('first') | list }}"
        descriptions: "{{ ip_data | map('split', ' ') | map('last') | list }}"

    - name: Voeg hosts toe aan AWX via de API met API-token
      uri:
        url: "http://185.107.90.120:31151/api/v2/hosts/"
        method: POST
        headers:
          Content-Type: "application/json"
          Authorization: "Bearer MoWalW6XysmG6hWmVB1tWHM3HhWhkW"  # API-token vervangen
        body:
          inventory: "Managed Plesk Servers"  # Naam van de inventaris
          name: "{{ item.0 }}"  # IP adres
          description: "{{ item.1 }}"  # Hostnaam
        body_format: json
        status_code: 201
      loop: "{{ hosts | zip(descriptions) | list }}"
